<?php

namespace Database\Seeders;

use App\Models\Rto;
use Illuminate\Database\Seeder;

class RtoSeeder extends Seeder
{
    public function run(): void
    {
        $rtos = [
            ['name' => 'CHENNAI (CENTRAL)',        'code' => 'TN01'],
            ['name' => 'CHENNAI (NORTH WEST)',      'code' => 'TN02'],
            ['name' => 'CHENNAI (NORTH-EAST)',      'code' => 'TN03'],
            ['name' => 'CHENNAI (EAST)',             'code' => 'TN04'],
            ['name' => 'CHENNAI (NORTH)',            'code' => 'TN05'],
            ['name' => 'CHENNAI (SOUTH-EAST)',       'code' => 'TN06'],
            ['name' => 'CHENNAI (SOUTH)',            'code' => 'TN07'],
            ['name' => 'CHENNAI (WEST)',             'code' => 'TN09'],
            ['name' => 'CHENNAI (SOUTH-WEST)',       'code' => 'TN10'],
            ['name' => 'TAMBARAM',                   'code' => 'TN11'],
            ['name' => 'POONAMALLEE',                'code' => 'TN12'],
            ['name' => 'AMBATTUR',                   'code' => 'TN13'],
            ['name' => 'SHOLINGANALLUR',             'code' => 'TN14'],
            ['name' => 'ULUNDURPET',                 'code' => 'TN15'],
            ['name' => 'KALLAKURICHI',               'code' => 'TN15Z'],
            ['name' => 'TINDIVANAM',                 'code' => 'TN16'],
            ['name' => 'GINGEE UO',                  'code' => 'TN16Z'],
            ['name' => 'REDHILLS',                   'code' => 'TN18'],
            ['name' => 'GUMMIDIPOONDI UO',           'code' => 'TN18Y'],
            ['name' => 'CHENGALPATTU',               'code' => 'TN19'],
            ['name' => 'THIRUKALUKUNTRAM UO',        'code' => 'TN19Y'],
            ['name' => 'MADURANTAGAM UO',            'code' => 'TN19Z'],
            ['name' => 'TIRUVALLUR',                 'code' => 'TN20'],
            ['name' => 'THIRUTHANI UO',              'code' => 'TN20X'],
            ['name' => 'KANCHEEPURAM',               'code' => 'TN21'],
            ['name' => 'MEENAMBAKKAM',               'code' => 'TN22'],
            ['name' => 'VELLORE',                    'code' => 'TN23'],
            ['name' => 'GUDIYATHAM UO',              'code' => 'TN23T'],
            ['name' => 'KRISHNAGIRI',                'code' => 'TN24'],
            ['name' => 'TIRUVANNAMALAI',             'code' => 'TN25'],
            ['name' => 'ERODE (EAST)',               'code' => 'TN33'],
            ['name' => 'TIRUCHI (WEST)',             'code' => 'TN45'],
            ['name' => 'MANAPARAI UO',               'code' => 'TN45Z'],
            ['name' => 'NAMAKKAL (NORTH)',           'code' => 'TN28'],
            ['name' => 'RASIPURAM UO',               'code' => 'TN28Z'],
            ['name' => 'DHARMAPURI',                 'code' => 'TN29'],
            ['name' => 'PALACODE UO',                'code' => 'TN29W'],
            ['name' => 'HARUR UO',                   'code' => 'TN29Z'],
            ['name' => 'SALEM (WEST)',               'code' => 'TN30'],
            ['name' => 'OMALURE UO',                 'code' => 'TN30W'],
            ['name' => 'CUDDALORE',                  'code' => 'TN31'],
            ['name' => 'PANRUTI UO',                 'code' => 'TN31Z'],
            ['name' => 'NEYVELI UO',                 'code' => 'TN31Y'],
            ['name' => 'VILUPPURAM',                 'code' => 'TN32'],
            ['name' => 'TIRUCHENGODE',               'code' => 'TN34'],
            ['name' => 'KUMARAPALAYAM',              'code' => 'TN34M'],
            ['name' => 'GOPICHETTIPALAYAM',          'code' => 'TN36'],
            ['name' => 'BHAVANI UO',                 'code' => 'TN36W'],
            ['name' => 'SATHYAMANGALAM UO',          'code' => 'TN36Z'],
            ['name' => 'COIMBATORE (SOUTH)',         'code' => 'TN37'],
            ['name' => 'SULUR UO',                   'code' => 'TN37Z'],
            ['name' => 'COIMBATORE (NORTH)',         'code' => 'TN38'],
            ['name' => 'TIRUPPUR (NORTH)',           'code' => 'TN39'],
            ['name' => 'AVINASHI UO',                'code' => 'TN39Z'],
            ['name' => 'METTUPALAYAM',               'code' => 'TN40'],
            ['name' => 'POLLACHI',                   'code' => 'TN41'],
            ['name' => 'VALPARAI UO',                'code' => 'TN41W'],
            ['name' => 'TIRUPPUR (SOUTH)',           'code' => 'TN42'],
            ['name' => 'KANGEYAM UO',                'code' => 'TN42Y'],
            ['name' => 'OOTY',                       'code' => 'TN43'],
            ['name' => 'GUDALORE UO',                'code' => 'TN43Z'],
            ['name' => 'PERAMBALUR',                 'code' => 'TN46'],
            ['name' => 'KARUR',                      'code' => 'TN47'],
            ['name' => 'MANMANGALAM UO',             'code' => 'TN47X'],
            ['name' => 'ARAVAKURICHI UO',            'code' => 'TN47Y'],
            ['name' => 'KULITHALI UO',               'code' => 'TN47Z'],
            ['name' => 'SRIRANGAM',                  'code' => 'TN48'],
            ['name' => 'LALKUDI UO',                 'code' => 'TN48X'],
            ['name' => 'MUSURI UO',                  'code' => 'TN48Y'],
            ['name' => 'THURAIYUR UO',               'code' => 'TN48Z'],
            ['name' => 'THANJAVUR',                  'code' => 'TN49'],
            ['name' => 'PATTUKOTTAI UO',             'code' => 'TN49Y'],
            ['name' => 'TIRUVARUR',                  'code' => 'TN50'],
            ['name' => 'THIRUTHURAIPOONDI UO',       'code' => 'TN50Y'],
            ['name' => 'MANNARGUDI UO',              'code' => 'TN50Z'],
            ['name' => 'NAGAPATTINAM',               'code' => 'TN51'],
            ['name' => 'SANKAGIRI',                  'code' => 'TN52'],
            ['name' => 'SALEM (EAST)',               'code' => 'TN54'],
            ['name' => 'PUDUKOTTAI',                 'code' => 'TN55'],
            ['name' => 'ALANGUDI UO',                'code' => 'TN55X'],
            ['name' => 'ILLUPPUR UO',                'code' => 'TN55Y'],
            ['name' => 'ARANTHANGI UO',              'code' => 'TN55Z'],
            ['name' => 'PERUNDURAI',                 'code' => 'TN56'],
            ['name' => 'DINDIGUL',                   'code' => 'TN57'],
            ['name' => 'NATHAM UO',                  'code' => 'TN57S'],
            ['name' => 'VEDACHANDUR UO',             'code' => 'TN57Y'],
            ['name' => 'BATLAGUNDU',                 'code' => 'TN57B'],
            ['name' => 'MADURAI (SOUTH)',            'code' => 'TN58'],
            ['name' => 'USILAMPATTI UO',             'code' => 'TN58Y'],
            ['name' => 'THIRUMANGALAM UO',           'code' => 'TN58Z'],
            ['name' => 'MADURAI (NORTH)',            'code' => 'TN59'],
            ['name' => 'VADIPATTI UO',               'code' => 'TN59V'],
            ['name' => 'MELUR UO',                   'code' => 'TN59Z'],
            ['name' => 'THENI',                      'code' => 'TN60'],
            ['name' => 'UTHAMAPALAYAM UO',           'code' => 'TN60Z'],
            ['name' => 'ARIYALUR',                   'code' => 'TN61'],
            ['name' => 'SIVAGANGAI',                 'code' => 'TN63'],
            ['name' => 'KARAIKUDI UO',               'code' => 'TN63Z'],
            ['name' => 'MADURAI (CENTRAL)',          'code' => 'TN64'],
            ['name' => 'RAMANATHAPURAM',             'code' => 'TN65'],
            ['name' => 'PARAMAKUDI UO',              'code' => 'TN65Z'],
            ['name' => 'COIMBATORE (CENTRAL)',       'code' => 'TN66'],
            ['name' => 'VIRUDHUNAGAR',               'code' => 'TN67'],
            ['name' => 'ARUPPUKOTTAI UO',            'code' => 'TN67W'],
            ['name' => 'KUMBAKONAM',                 'code' => 'TN68'],
            ['name' => 'THOOTHUKUDI',                'code' => 'TN69'],
            ['name' => 'HOSUR',                      'code' => 'TN70'],
            ['name' => 'TIRUNELVELI',                'code' => 'TN72'],
            ['name' => 'VALLIYUR UO',                'code' => 'TN72V'],
            ['name' => 'RANIPET',                    'code' => 'TN73'],
            ['name' => 'ARAKKONAM UO',               'code' => 'TN73Z'],
            ['name' => 'NAGERCOIL',                  'code' => 'TN74'],
            ['name' => 'MARTHANDAM',                 'code' => 'TN75'],
            ['name' => 'TENKASI',                    'code' => 'TN76'],
            ['name' => 'AMBASAMUTHIRAM UO',          'code' => 'TN76V'],
            ['name' => 'ALANGULAM UO',               'code' => 'TN76B'],
            ['name' => 'ATTUR',                      'code' => 'TN77'],
            ['name' => 'VALAPPADI UO',               'code' => 'TN77Z'],
            ['name' => 'DHARAPURAM',                 'code' => 'TN78'],
            ['name' => 'UDUMALPET',                  'code' => 'TN78Z'],
            ['name' => 'SANKARANKOVIL',              'code' => 'TN79'],
            ['name' => 'TIRUCHI(EAST)',              'code' => 'TN81'],
            ['name' => 'TIRUVERANBUR UO',            'code' => 'TN81Z'],
            ['name' => 'MAYILADUTHURAI',             'code' => 'TN82'],
            ['name' => 'SIRKALI UO',                 'code' => 'TN82Z'],
            ['name' => 'VANIYAMBADI',                'code' => 'TN83'],
            ['name' => 'AMBUR UO',                   'code' => 'TN83Y'],
            ['name' => 'THIRUPATTUR',                'code' => 'TN83Z'],
            ['name' => 'SRIVILLIPUTHUR',             'code' => 'TN84'],
            ['name' => 'RAJAPALAYAM UO',             'code' => 'TN84U'],
            ['name' => 'KUNDRATHUR',                 'code' => 'TN85'],
            ['name' => 'ERODE (WEST)',               'code' => 'TN86'],
            ['name' => 'SRIPERUMBUDUR',              'code' => 'TN87'],
            ['name' => 'NAMAKKAL (SOUTH)',           'code' => 'TN88'],
            ['name' => 'PARAMATHI VELLURE UO',       'code' => 'TN88Z'],
            ['name' => 'SALEM (SOUTH)',              'code' => 'TN90'],
            ['name' => 'CHIDAMBARAM',                'code' => 'TN91'],
            ['name' => 'VIRUDHACHALAM UO',           'code' => 'TN91Z'],
            ['name' => 'THIRUCHENDUR',               'code' => 'TN92'],
            ['name' => 'METTUR',                     'code' => 'TN93'],
            ['name' => 'PALANI',                     'code' => 'TN94'],
            ['name' => 'ODDANCHATRAM UO',            'code' => 'TN94Z'],
            ['name' => 'SIVAKASI',                   'code' => 'TN95'],
            ['name' => 'KOVILPATTI',                 'code' => 'TN96'],
            ['name' => 'ARANI',                      'code' => 'TN97'],
            ['name' => 'CHEYYAR UO',                 'code' => 'TN97Z'],
            ['name' => 'COIMBATORE (WEST)',          'code' => 'TN99'],
        ];

        foreach ($rtos as $rto) {
            Rto::updateOrCreate(['code' => $rto['code']], $rto);
        }
    }
}
